"""Изменение модели заказа

Revision ID: 2d9a1b23c07c
Revises: 8d676f024d87
Create Date: 2025-07-20 19:09:49.775237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9a1b23c07c'
down_revision = '8d676f024d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordered_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment', sa.String(length=20), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('payment')
        batch_op.drop_column('delivery_method')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('created_time')

    with op.batch_alter_table('ordered_products', schema=None) as batch_op:
        batch_op.drop_column('created_timestamp')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
